networks:
  inception:
    name: $NETWORK_NAME
    driver: bridge

volumes:
  mariadb:
    driver_opts:
      type: none
      device: /home/sbelomet/data/mariadb
      o: bind
    name: mariadb

  wordpress:
    driver_opts:
      type: none
      device: /home/sbelomet/data/wordpress
      o: bind
    name: wordpress

services:
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: nginx:1337
    restart: on-failure
    networks:
      - $NETWORK_NAME
    expose:
      - "443"
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      - wordpress

  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: mariadb:1337
    restart: on-failure
    networks:
      - $NETWORK_NAME
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress:1337
    restart: on-failure
    networks:
      - $NETWORK_NAME
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    depends_on:
      mariadb:
        condition: service_healthy
        restart: false